name: Terraform CI/CD
run-name: Infra CI/CD

on:
  push:
    branches: [main, infra]
    paths: &infra_paths
      - infra/**
      - .github/workflows/terraform.yml
      - .github/actions/terraform/action.yml
      - scripts/**

  pull_request:
    branches: [main, infra]
    paths: *infra_paths

  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  contents: read
  id-token: write # Required for requesting the singed JWT token.
  pull-requests: write
  issues: write
  security-events: write


defaults:
  run:
    shell: bash

env:
  AWS_REGION: eu-central-1
  INFRA_DIR: infra
  TERRAFORM_VERSION: 1.11.0

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "${{ env.INFRA_DIR }}"
    steps:
      - name: Checkout the infra code
        uses: actions/checkout@v4
        with:
          ref: infra
          fetch-depth: 0

      - name: Setup Terraform
        uses: ./.github/actions/terraform
        with:
          terraform_version: "${{ env.TERRAFORM_VERSION }}"
          terraform_wrapper: false
          public_key: "${{ vars.PUBLIC_KEY }}"
          role_to_assume: "${{ secrets.AWS_OIDC_ROLE }}"
          aws_region: "${{env.AWS_REGION}}"
          role_session_name: "OIDC-Session"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Start a debug session
        if: failure()
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true

  security-scan:
    name: Security Scan with Checkov
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - name: Checkout the infra code
        uses: actions/checkout@v4
        with:
          ref: infra
          fetch-depth: 0

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: "${{ env.INFRA_DIR }}"
          framework: terraform
          quiet: true
          soft_fail: true
          output_format: sarif
          output_file_path: checkov.sarif

      - name: Upload Checkov results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: checkov.sarif

  plan:
    name: Terraform plan
    needs: [validate]
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: "${{ env.INFRA_DIR }}"
    steps:
      - name: Checkout the infra code
        uses: actions/checkout@v4
        with:
          ref: infra
          fetch-depth: 0

      - name: Setup Terraform
        uses: ./.github/actions/terraform
        with:
          terraform_version: "${{ env.TERRAFORM_VERSION }}"
          terraform_wrapper: false
          public_key: "${{ vars.PUBLIC_KEY }}"
          role_to_assume: "${{ secrets.AWS_OIDC_ROLE }}"
          aws_region: "${{env.AWS_REGION}}"
          role_session_name: "OIDC-Session"

      - name: Terraform Init
        run: terraform init -migrate-state

      - name: Terraform plan
        env:
          TF_VAR_test_instance_type: "${{ vars.TEST_INSTANCE_TYPE }}"
          TF_VAR_test_security_group_id: "${{ vars.TEST_SECURITY_GROUP_ID }}"
        id: plan
        run: terraform plan -no-color -input=false -var-file="prod.tfvars"
        continue-on-error: true

      - name: "Update the pull request"
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          PLAN: "${{ steps.plan.outputs.stdout }}"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const output =`
              #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

              <details><summary>Show Plan</summary>

              \`\`\`\n
              ${process.env.PLAN}
              \`\`\`

              </details>

              *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
            })

      - name: Start a debug session
        if: failure()
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true

  apply:
    name: Terraform apply
    needs: [plan]
    if: github.ref == 'refs/heads/main' && github.event.inputs.action == 'apply'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.apply.outputs.website_url }}
    defaults:
      run:
        working-directory: "${{ env.INFRA_DIR }}"
    steps:
      - name: Checkout the infra code
        uses: actions/checkout@v4
        with:
          ref: infra
          fetch-depth: 0

      - name: Setup Terraform
        uses: ./.github/actions/terraform
        with:
          terraform_version: "${{ env.TERRAFORM_VERSION }}"
          terraform_wrapper: false
          public_key: "${{ vars.PUBLIC_KEY }}"
          role_to_assume: "${{ secrets.AWS_OIDC_ROLE }}"
          aws_region: "${{env.AWS_REGION}}"
          role_session_name: "OIDC-Session"

      - name: Terraform Init
        run: terraform init -migrate-state

      - name: Terraform apply
        id: apply
        env:
          TF_VAR_test_instance_type: "${{ vars.TEST_INSTANCE_TYPE }}"
          TF_VAR_test_security_group_id: "${{ vars.TEST_SECURITY_GROUP_ID }}"

        run: |
          terraform apply -auto-approve -var-file="prod.tfvars"

          # Get the outputs
          public_ip=$(terraform output -raw public_ip 2>/dev/null || echo "")
          website_url=$(terraform output -raw public_dns 2>/dev/null || echo "")

          echo "public_ip=${public_ip}" >> $GITHUB_OUTPUT
          echo "website_url=${website_url}" >> $GITHUB_OUTPUT

      - name: Update deployment status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ steps.apply.outcome }}';
            const publicIP = '${{ steps.apply.outputs.public_ip }}';
            const websiteUrl = '${{ steps.apply.outputs.website_url }}';

            if (status === 'success') {
              console.log(`✅ Successfully deployed latest changes`);
              console.log(`🌐 Public IP: ${publicIP}`);
              console.log(`🌐 Public DNS: ${websiteUrl}`);
            } else {
              console.log(`❌ Deployment to failed`);
            }

      - name: Start a debug session
        if: failure()
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true

  destroy:
    name: Terraform destroy
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
    runs-on: ubuntu-latest
    environment: production
    continue-on-error: true
    steps:
        - name: Checkout the code
          uses: actions/checkout@v4

        - name: Setup Terraform
          uses: ./.github/actions/terraform
          with:
            terraform_version: "${{ env.TERRAFORM_VERSION }}"
            terraform_wrapper: false
            public_key: "${{ vars.PUBLIC_KEY }}"
            role_to_assume: "${{ secrets.AWS_OIDC_ROLE }}"
            aws_region: "${{env.AWS_REGION}}"
            role_session_name: "OIDC-Session"

        - name: Terraform Init
          run: terraform init -migrate-state

        - name: Terraform destroy
          run: |
            terraform destroy -auto-approve -var-file="prod.tfvars"
