name: Terraform CI/CD
run-name: Infra CI/CD

on:
  push:
    branches: [main, infra]
    paths:
      - infra/**
      - .github/workflows/terraform.yml
      - .github/actions/terraform/action.yml
      - scripts/**

  pull_request:
    branches: [main, infra]
    paths:
      - infra/**
      - .github/workflows/terraform.yml
      - .github/actions/terraform/action.yml
      - scripts/**

  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  contents: read
  id-token: write # Required for requesting the singed jwt token.

defaults:
  run:
    shell: bash

env:
  AWS_REGION: eu-central-1

jobs:
  ci:
    name: Terraform CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the infra code
        uses: actions/checkout@v4
        with:
          ref: infra

      - name: Setup Terraform
        uses: ./.github/actions/terraform
        with:
          terraform_version: 1.11.0
          terraform_wrapper: false
          role_to_assume: "${{ secrets.AWS_OIDC_ROLE }}"
          aws_region: "$AWS_REGION"
          role_session_name: "OIDC-Session"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: List the S3 buckets
        run:
          echo "Here are the buckets"
          aws s3 ls
